/**
 * @reference https://projecteuler.net/problem=12
 * @description  The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * @problem What is the value of the first triangle number to have over five hundred divisors?
 *
 * @solution 125250
 * iojs prob-12.js
*/

'use strict';

/**
 * Return triangle number with nth number of divisors
 * @param  {int} divs [number of divisors final int will have]
 * @return {int}      [final int]
 */
function getTriNum(divs) {
	return divs * (divs + 1) / 2;
}

console.log( getTriNum(500) );
