# https://projecteuler.net/problem=2

# Each new term in the fibsnacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the fibsnacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# @solution 4613732

# ruby prob-2.rb

def fibs(limit)
	fibs = [0, 1, 1]

	until fibs[ fibs.length - 1 ] > limit
		fibs.push( fibs[fibs.length - 1] + fibs[fibs.length - 2] )
	end

	return fibs
end

def calcEvens(fibs)
	fibs.find_all do |i|
		i % 2 == 0
	end.reduce(:+)
end

puts calcEvens( fibs(4000000) )
