# https://projecteuler.net/problem=2

# Each new term in the fibsnacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the fibsnacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# @solution 4613732

# rScript prob-2.R

# initialize am empty vector
fibz <- c( 0, 1, 1 )
limit = 4000000

while ( fibz[length(fibz) - 1] < limit ) {
	fibz <- c( fibz, fibz[length(fibz) - 1] + fibz[length(fibz) - 2] )
	print(fibz[length(fibz) - 1])
}

# creates the barchart and puts it at ./fizzbuzz.gif
png( 'fibz.png',
	width     = 1200,
	height    = 1200,
	units     = "px",
	res       = 72
)
barplot( fibz, main='Fibz Distribution',
	ylab='Amount' )
dev.off()
