###
https://projecteuler.net/problem=2

Each new term in the fibznacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the fibznacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

@solution 4613732

iojs prob-2-fibonacci.js
###

present = require('present')

do ->
	'use strict'
	limit = 4000000
	start = present()

	fibonacci = ->
		i = 1
		value = 0
		fibo = [0]

		# for i in [1..50] by 1
		while value < limit
			if i is 1
				value = i
			else if fibo[i-1] < limit
				value = fibo[i-2] + fibo[i-1]

			# console.log value
			fibo.push(value)
			i++

		calcEvens(fibo)


	calcEvens = (fibo) ->
		len = fibo.length
		sum = 0

		while len--
			if fibo[len] % 2 == 0
				sum += fibo[len]

		console.log sum
		console.log 'op took: ' + (present() - start) + ' ms.'


	fibonacci()
